system_configuration:
    groups:
        hack_oro:
            title: 'hack_oro.label'
        hack_oro_customer_tracking:
            icon: 'fa-eye'
            title: 'hack_oro.customer_tracking.label'
        logrocket:
            title: 'hack_oro.customer_tracking.logrocket.label'
        fullstory:
            title: 'hack_oro.customer_tracking.fullstory.label'
        hotjar:
            title: 'hack_oro.customer_tracking.hotjar.label'
    fields:
        hack_oro_customer_tracking.logrocket_is_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 30
            options:
                label: 'hack_oro.customer_tracking.logrocket.is_enabled.label'
        hack_oro_customer_tracking.logrocket_app_id:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            options:
                label: 'hack_oro.customer_tracking.logrocket.app_id.label'
                tooltip: 'hack_oro.customer_tracking.logrocket.app_id.help'
        hack_oro_customer_tracking.fullstory_is_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 30
            options:
                label: 'hack_oro.customer_tracking.fullstory.is_enabled.label'
        hack_oro_customer_tracking.fullstory_org:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            options:
                label: 'hack_oro.customer_tracking.fullstory.org.label'
                tooltip: 'hack_oro.customer_tracking.fullstory.org.help'
        hack_oro_customer_tracking.fullstory_debug_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 30
            options:
                label: 'hack_oro.customer_tracking.fullstory.debug_enabled.label'
        hack_oro_customer_tracking.fullstory_namespace:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            options:
                label: 'hack_oro.customer_tracking.fullstory.namespace.label'
        hack_oro_customer_tracking.hotjar_is_enabled:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 30
            options:
                label: 'hack_oro.customer_tracking.hotjar.is_enabled.label'
        hack_oro_customer_tracking.hotjar_site_id:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            options:
                label: 'hack_oro.customer_tracking.hotjar.site_id.label'

    tree:
        system_configuration:
            platform:
                children:
                    hack_oro:
                        children:
                            hack_oro_customer_tracking:
                                children:
                                    logrocket:
                                        children:
                                            - hack_oro_customer_tracking.logrocket_is_enabled
                                            - hack_oro_customer_tracking.logrocket_app_id
                                    fullstory:
                                        children:
                                            - hack_oro_customer_tracking.fullstory_is_enabled
                                            - hack_oro_customer_tracking.fullstory_org
                                            - hack_oro_customer_tracking.fullstory_debug_enabled
                                            - hack_oro_customer_tracking.fullstory_namespace
                                    hotjar:
                                        children:
                                            - hack_oro_customer_tracking.hotjar_is_enabled
                                            - hack_oro_customer_tracking.hotjar_site_id

        website_configuration:
            platform:
                children:
                    hack_oro:
                        children:
                            hack_oro_customer_tracking:
                                children:
                                    logrocket:
                                        children:
                                            - hack_oro_customer_tracking.logrocket_is_enabled
                                            - hack_oro_customer_tracking.logrocket_app_id
                                    fullstory:
                                        children:
                                            - hack_oro_customer_tracking.fullstory_is_enabled
                                            - hack_oro_customer_tracking.fullstory_org
                                            - hack_oro_customer_tracking.fullstory_debug_enabled
                                            - hack_oro_customer_tracking.fullstory_namespace
                                    hotjar:
                                        children:
                                            - hack_oro_customer_tracking.hotjar_is_enabled
                                            - hack_oro_customer_tracking.hotjar_site_id